unit TestuEntradaSaidaEstoque;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, FireDAC.Stan.Option, FireDAC.DApt.Intf, FireDAC.DatS,
  FireDAC.Stan.Param, uEntradaSaidaEstoque, System.Classes, Vcl.ExtCtrls,
  Vcl.StdCtrls, FireDAC.Stan.Intf, Vcl.Samples.Spin, FireDAC.Stan.Error, Vcl.Graphics,
  FireDAC.Phys.Intf, FireDAC.Comp.Client, Vcl.DBCtrls, Winapi.Windows,
  System.Variants, Winapi.Messages, Vcl.Dialogs, FireDAC.Stan.Async,
  FireDAC.DApt, Vcl.Forms, System.SysUtils, Data.DB, Vcl.Controls, Vcl.Mask,
  FireDAC.Comp.DataSet;

type
  // Test methods for class TfEntradaSaidaEstoque

  TestTfEntradaSaidaEstoque = class(TTestCase)
  strict private
    FfEntradaSaidaEstoque: TfEntradaSaidaEstoque;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSomarEstoque;
    procedure TestSubtrairEstoque;
  end;

implementation

procedure TestTfEntradaSaidaEstoque.SetUp;
begin
  FfEntradaSaidaEstoque := TfEntradaSaidaEstoque.Create(nil);
end;

procedure TestTfEntradaSaidaEstoque.TearDown;
begin
  FfEntradaSaidaEstoque.Free;
  FfEntradaSaidaEstoque := nil;
end;

procedure TestTfEntradaSaidaEstoque.TestSomarEstoque;
var
  ReturnValue: Double;
  ANumero2: Double;
  ANumero1: Double;
begin
  ANumero1 := 2;
  ANumero2 := 2;

  ReturnValue := FfEntradaSaidaEstoque.SomarEstoque(ANumero1, ANumero2);

  CheckEquals(4, ReturnValue, 'A Função SomarEstoque Falhou')
end;

procedure TestTfEntradaSaidaEstoque.TestSubtrairEstoque;
var
  ReturnValue: Double;
  ANumero2: Double;
  ANumero1: Double;
begin
  ANumero1 := 2;
  ANumero2 := 2;

  ReturnValue := FfEntradaSaidaEstoque.SubtrairEstoque(ANumero1, ANumero2);

  CheckEquals(0, ReturnValue, 'A Função SubtrairEstoque Falhou');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfEntradaSaidaEstoque.Suite);
end.

